db1:
  type: mysql
  addr: 192.168.1.10:3306
  username: user
  password: paasword
  database: registry
db5:
  type: mysql
  addr: 192.168.1.16:3306
  username: user
  password: paasword
  database: registry
